### ISSUE TITLE
Installation of transcript_utils and Sargasso fails in initial setup script.

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#223]
It seems to be due to this issue:

https://github.com/pypa/setuptools/issues/4483

and the fix appears to be to make sure that the version of the "packaging" package is >= 22.0.

**Comment by lweasel** [comment]
Ok, unfortunately this "fix" has broken other things, namely I now get this when running multiqc:

Traceback (most recent call last):
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3395, in _dep_map
    return self.__dep_map
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3175, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/bin/multiqc", line 5, in <module>
    from multiqc.__main__ import multiqc
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/multiqc/__main__.py", line 53, in <module>
    multiqc.run_cli(prog_name="multiqc")
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/multiqc/multiqc.py", line 212, in run_cli
    multiqc_run = run(
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/multiqc/multiqc.py", line 549, in run
    template_mod = config.avail_templates[config.template].load()
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2770, in load
    self.require(*args, **kwargs)  # type: ignore
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2798, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3098, in requires
    dm = self._dep_map
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3397, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3414, in _compute_dependencies
    common = types.MappingProxyType(dict.fromkeys(reqs_for_extra(None)))
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3411, in reqs_for_extra
    if not req.marker or req.marker.evaluate({'extra': extra}):
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/packaging/markers.py", line 241, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/packaging/markers.py", line 150, in _evaluate_markers
    lhs_value, rhs_value = _normalize(lhs_value, rhs_value, key=environment_key)
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/packaging/markers.py", line 124, in _normalize
    return tuple(canonicalize_name(v) for v in values)
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/packaging/markers.py", line 124, in <genexpr>
    return tuple(canonicalize_name(v) for v in values)
  File "/home/odando/.virtualenvs/gsgq_dreadd_2024/lib/python3.8/site-packages/packaging/utils.py", line 34, in canonicalize_name
    value = _canonicalize_regex.sub("-", name).lower()
TypeError: expected string or bytes-like object
